;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-word-begin
	evil-change
	evil-find-char
	evil-forward-word-begin
	evil-insert
	evil-normal-state
	evil-previous-line
	multiple-cursors-mode
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-exit-emacs-state
	evil-forward-char
	evil-forward-word-end
	evil-goto-first-line
	evil-goto-line
	evil-goto-mark-line
	evil-insert-line
	evil-next-line
	evil-repeat-find-char
	markdown-outdent-or-delete
	))
